[workspace]
resolver = "2"
members = ["cove", "cove-*"]

[workspace.package]
version = "0.6.1"
edition = "2021"

[workspace.dependencies]
crossterm = "0.26.1"
serde = { version = "1.0.159", features = ["derive"] }
serde_either = "0.2.1"
thiserror = "1.0.40"

[profile.dev.package."*"]
opt-level = 3
