[package]
name = "cove"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
async-trait = "0.1.56"
clap = { version = "3.2.14", features = ["derive"] }
crossterm = "0.24.0"
directories = "4.0.1"
edit = "0.1.4"
futures = "0.3.21"
log = { version = "0.4.17", features = ["std"] }
palette = { version = "0.6.1", default-features = false, features = ["std"] }
parking_lot = "0.12.1"
rand = "0.8.5"
rusqlite = { version = "0.28.0", features = ["bundled", "time"] }
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.82"
thiserror = "1.0.31"
tokio = { version = "1.20.0", features = ["full"] }
unicode-segmentation = "1.9.0"
unicode-width = "0.1.9"
cookie = "0.16.0"

[dependencies.time]
version = "0.3.11"
features = ["macros", "formatting", "parsing", "serde"]

[dependencies.tokio-tungstenite]
version = "0.17.2"
features = ["rustls-tls-native-roots"]

[dependencies.toss]
git = "https://github.com/Garmelon/toss.git"
rev = "dfc10f9d092bf9ac85a8718f1b80df28aeb0ec23"

# [patch."https://github.com/Garmelon/toss.git"]
# toss = { path = "../toss/" }
