[package]
name = "cove"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
async-trait = "0.1.56"
chrono = { version = "0.4.19", features = ["serde"] }
clap = { version = "3.2.12", features = ["derive"] }
crossterm = "0.24.0"
directories = "4.0.1"
edit = "0.1.4"
futures = "0.3.21"
log = { version = "0.4.17", features = ["std"] }
palette = { version = "0.6.0", default-features = false, features = ["std"] }
parking_lot = "0.12.1"
rand = "0.8.5"
rusqlite = { version = "0.28.0", features = ["bundled", "chrono"] }
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.82"
thiserror = "1.0.31"
tokio = { version = "1.20.0", features = ["full"] }
unicode-segmentation = "1.9.0"
unicode-width = "0.1.9"

[dependencies.tokio-tungstenite]
version = "0.17.2"
features = ["rustls-tls-native-roots"]

[dependencies.toss]
git = "https://github.com/Garmelon/toss.git"
rev = "c1907bb8ee215d534daf4188824293203b60dd9c"

# [patch."https://github.com/Garmelon/toss.git"]
# toss = { path = "../toss/" }
