[package]
name = "cove"
version = "0.4.0"
edition = "2021"

[dependencies]
anyhow = "1.0.63"
async-trait = "0.1.57"
clap = { version = "3.2.19", features = ["derive"] }
cookie = "0.16.0"
crossterm = "0.25.0"
directories = "4.0.1"
edit = "0.1.4"
log = { version = "0.4.17", features = ["std"] }
open = "3.0.2"
parking_lot = "0.12.1"
rusqlite = { version = "0.28.0", features = ["bundled", "time"] }
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
thiserror = "1.0.33"
tokio = { version = "1.20.1", features = ["full"] }
toml = "0.5.9"
unicode-segmentation = "1.9.0"
unicode-width = "0.1.9"
linkify = "0.9.0"

[dependencies.time]
version = "0.3.14"
features = ["macros", "formatting", "parsing", "serde"]

[dependencies.tokio-tungstenite]
version = "0.17.2"
features = ["rustls-tls-native-roots"]

[dependencies.euphoxide]
git = "https://github.com/Garmelon/euphoxide.git"
rev = "01a442c1f0695bd11b8f54db406b3a3a03d61983"

# [patch."https://github.com/Garmelon/euphoxide.git"]
# euphoxide = { path = "../euphoxide/" }

[dependencies.toss]
git = "https://github.com/Garmelon/toss.git"
rev = "45ece466c235cce6e998bbd404f915cad3628c8c"

# [patch."https://github.com/Garmelon/toss.git"]
# toss = { path = "../toss/" }
