[package]
name = "cove"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.61"
async-trait = "0.1.57"
clap = { version = "3.2.16", features = ["derive"] }
cookie = "0.16.0"
crossterm = "0.25.0"
directories = "4.0.1"
edit = "0.1.4"
futures = "0.3.21"
log = { version = "0.4.17", features = ["std"] }
palette = { version = "0.6.1", default-features = false, features = ["std"] }
parking_lot = "0.12.1"
rand = "0.8.5"
rusqlite = { version = "0.28.0", features = ["bundled", "time"] }
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["full"] }
unicode-segmentation = "1.9.0"
unicode-width = "0.1.9"

[dependencies.time]
version = "0.3.13"
features = ["macros", "formatting", "parsing", "serde"]

[dependencies.tokio-tungstenite]
version = "0.17.2"
features = ["rustls-tls-native-roots"]

[dependencies.toss]
git = "https://github.com/Garmelon/toss.git"
rev = "45ece466c235cce6e998bbd404f915cad3628c8c"

# [patch."https://github.com/Garmelon/toss.git"]
# toss = { path = "../toss/" }
