[package]
name = "cove"
version = "0.5.2"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
async-trait = "0.1.64"
clap = { version = "4.1.4", features = ["derive", "deprecated"] }
cookie = "0.17.0"
crossterm = "0.26.0"
directories = "4.0.1"
edit = "0.1.4"
linkify = "0.9.0"
log = { version = "0.4.17", features = ["std"] }
once_cell = "1.17.0"
open = "3.2.0"
parking_lot = "0.12.1"
rusqlite = { version = "0.28.0", features = ["bundled", "time"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
thiserror = "1.0.38"
tokio = { version = "1.25.0", features = ["full"] }
toml = "0.7.2"
unicode-segmentation = "1.10.1"
unicode-width = "0.1.10"

[dependencies.time]
version = "0.3.17"
features = ["macros", "formatting", "parsing", "serde"]

[dependencies.tokio-tungstenite]
version = "0.18.0"
features = ["rustls-tls-native-roots"]

[dependencies.euphoxide]
git = "https://github.com/Garmelon/euphoxide.git"
rev = "768a259f02f5743f7812904657a99f1f58b8e835"
features = ["bot"]

# [patch."https://github.com/Garmelon/euphoxide.git"]
# euphoxide = { path = "../euphoxide/" }

[dependencies.toss]
git = "https://github.com/Garmelon/toss.git"
rev = "0d59116012a51516a821991e2969b1cf4779770f"

# [patch."https://github.com/Garmelon/toss.git"]
# toss = { path = "../toss/" }

[dependencies.vault]
git = "https://github.com/Garmelon/vault.git"
tag = "v0.1.0"
features = ["tokio"]

# [patch."https://github.com/Garmelon/vault.git"]
# vault = { path = "../vault/" }
