[workspace]
resolver = "2"
members = ["cove", "cove-*"]

[workspace.package]
version = "0.6.1"
edition = "2021"

[workspace.dependencies]
crossterm = "0.26.1"
parking_lot = "0.12.1"
serde = { version = "1.0.159", features = ["derive"] }
serde_either = "0.2.1"
thiserror = "1.0.40"

[workspace.dependencies.toss]
git = "https://github.com/Garmelon/toss.git"
rev = "6eb853e3136dd320272bd67e2957774869c21e4b"

[profile.dev.package."*"]
opt-level = 3
