[workspace]
resolver = "2"
members = ["cove", "cove-*"]

[workspace.package]
version = "0.8.3"
edition = "2021"

[workspace.dependencies]
crossterm = "0.27.0"
parking_lot = "0.12.2"
serde = { version = "1.0.202", features = ["derive"] }
serde_either = "0.2.1"
thiserror = "1.0.61"

[workspace.dependencies.toss]
git = "https://github.com/Garmelon/toss.git"
tag = "v0.2.3"

[workspace.lints]
rust.unsafe_code = { level = "forbid", priority = 1 }
# Lint groups
rust.deprecated_safe = "warn"
rust.future_incompatible = "warn"
rust.keyword_idents = "warn"
rust.rust_2018_idioms = "warn"
rust.unused = "warn"
# Individual lints
rust.non_local_definitions = "warn"
rust.redundant_imports = "warn"
rust.redundant_lifetimes = "warn"
rust.single_use_lifetimes = "warn"
rust.unit_bindings = "warn"
rust.unnameable_types = "warn"
rust.unused_crate_dependencies = "warn"
rust.unused_import_braces = "warn"
rust.unused_lifetimes = "warn"
rust.unused_qualifications = "warn"
# Clippy
clippy.use_self = "warn"


[profile.dev.package."*"]
opt-level = 3
