[package]
name = "cove"
version = "0.5.1"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1.58"
clap = { version = "4.0.27", features = ["derive", "deprecated"] }
cookie = "0.16.1"
crossterm = "0.25.0"
directories = "4.0.1"
edit = "0.1.4"
log = { version = "0.4.17", features = ["std"] }
open = "3.2.0"
parking_lot = "0.12.1"
rusqlite = { version = "0.28.0", features = ["bundled", "time"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.89"
thiserror = "1.0.37"
tokio = { version = "1.22.0", features = ["full"] }
toml = "0.5.9"
unicode-segmentation = "1.10.0"
unicode-width = "0.1.10"
linkify = "0.9.0"

[dependencies.time]
version = "0.3.17"
features = ["macros", "formatting", "parsing", "serde"]

[dependencies.tokio-tungstenite]
version = "0.17.2"
features = ["rustls-tls-native-roots"]

[dependencies.euphoxide]
git = "https://github.com/Garmelon/euphoxide.git"
rev = "f5ba899a364b78afdf063d864cfa3f6287ddf11b"

# [patch."https://github.com/Garmelon/euphoxide.git"]
# euphoxide = { path = "../euphoxide/" }

[dependencies.toss]
git = "https://github.com/Garmelon/toss.git"
rev = "06aefd562bd66f5564f7c1ea73a4959f51be74e7"

# [patch."https://github.com/Garmelon/toss.git"]
# toss = { path = "../toss/" }
