[workspace]
resolver = "2"
members = ["cove", "cove-*"]

[workspace.package]
version = "0.7.0"
edition = "2021"

[workspace.dependencies]
crossterm = "0.27.0"
parking_lot = "0.12.1"
serde = { version = "1.0.188", features = ["derive"] }
serde_either = "0.2.1"
thiserror = "1.0.47"

[workspace.dependencies.toss]
git = "https://github.com/Garmelon/toss.git"
tag = "v0.2.0"

[profile.dev.package."*"]
opt-level = 3
