[package]
name = "cove"
version = "0.6.1"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
async-recursion = "1.0.4"
async-trait = "0.1.68"
clap = { version = "4.2.1", features = ["derive", "deprecated"] }
cookie = "0.17.0"
crossterm = "0.26.1"
directories = "5.0.0"
edit = "0.1.4"
linkify = "0.9.0"
log = { version = "0.4.17", features = ["std"] }
once_cell = "1.17.1"
open = "4.0.1"
parking_lot = "0.12.1"
rusqlite = { version = "0.28.0", features = ["bundled", "time"] }
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
thiserror = "1.0.40"
tokio = { version = "1.27.0", features = ["full"] }
toml = "0.7.3"
unicode-segmentation = "1.10.1"
unicode-width = "0.1.10"

[dependencies.time]
version = "0.3.20"
features = ["macros", "formatting", "parsing", "serde"]

[dependencies.tokio-tungstenite]
version = "0.18.0"
features = ["rustls-tls-native-roots"]

[dependencies.euphoxide]
git = "https://github.com/Garmelon/euphoxide.git"
rev = "0f217a6279181b0731216760219e8ff0fa01e449"
features = ["bot"]

# [patch."https://github.com/Garmelon/euphoxide.git"]
# euphoxide = { path = "../euphoxide/" }

[dependencies.toss]
git = "https://github.com/Garmelon/toss.git"
rev = "59710c816269c434b97ece3ab1701d3fef2269cb"

# [patch."https://github.com/Garmelon/toss.git"]
# toss = { path = "../toss/" }

[dependencies.vault]
git = "https://github.com/Garmelon/vault.git"
tag = "v0.1.0"
features = ["tokio"]

# [patch."https://github.com/Garmelon/vault.git"]
# vault = { path = "../vault/" }

[profile.dev.package."*"]
opt-level = 3
