[package]
name = "cove"
version = "0.4.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
async-trait = "0.1.57"
clap = { version = "3.2.22", features = ["derive"] }
cookie = "0.16.1"
crossterm = "0.25.0"
directories = "4.0.1"
edit = "0.1.4"
log = { version = "0.4.17", features = ["std"] }
open = "3.0.3"
parking_lot = "0.12.1"
rusqlite = { version = "0.28.0", features = ["bundled", "time"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
thiserror = "1.0.36"
tokio = { version = "1.21.1", features = ["full"] }
toml = "0.5.9"
unicode-segmentation = "1.10.0"
unicode-width = "0.1.10"
linkify = "0.9.0"

[dependencies.time]
version = "0.3.14"
features = ["macros", "formatting", "parsing", "serde"]

[dependencies.tokio-tungstenite]
version = "0.17.2"
features = ["rustls-tls-native-roots"]

[dependencies.euphoxide]
git = "https://github.com/Garmelon/euphoxide.git"
rev = "bdb17db5bf4796696d6375168abb76920ab11b87"

# [patch."https://github.com/Garmelon/euphoxide.git"]
# euphoxide = { path = "../euphoxide/" }

[dependencies.toss]
git = "https://github.com/Garmelon/toss.git"
rev = "06aefd562bd66f5564f7c1ea73a4959f51be74e7"

# [patch."https://github.com/Garmelon/toss.git"]
# toss = { path = "../toss/" }
