[package]
name = "cove"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
cove-config = { path = "../cove-config" }
cove-input = { path = "../cove-input" }

crossterm = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }
toss = { workspace = true }

anyhow = "1.0.75"
async-trait = "0.1.73"
clap = { version = "4.4.1", features = ["derive", "deprecated"] }
cookie = "0.17.0"
directories = "5.0.1"
linkify = "0.10.0"
log = { version = "0.4.20", features = ["std"] }
once_cell = "1.18.0"
open = "5.0.0"
rusqlite = { version = "0.29.0", features = ["bundled", "time"] }
serde_json = "1.0.105"
tokio = { version = "1.32.0", features = ["full"] }
unicode-segmentation = "1.10.1"
unicode-width = "0.1.10"

[dependencies.time]
version = "0.3.28"
features = ["macros", "formatting", "parsing", "serde"]

[dependencies.tokio-tungstenite]
version = "0.20.0"
features = ["rustls-tls-native-roots"]

[dependencies.euphoxide]
git = "https://github.com/Garmelon/euphoxide.git"
tag = "v0.4.0"
features = ["bot"]

[dependencies.vault]
git = "https://github.com/Garmelon/vault.git"
tag = "v0.2.0"
features = ["tokio"]
