[package]
name = "cove"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
cove-config = { path = "../cove-config" }
cove-input = { path = "../cove-input" }

crossterm = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }
toss = { workspace = true }

anyhow = "1.0.70"
async-trait = "0.1.68"
clap = { version = "4.2.1", features = ["derive", "deprecated"] }
cookie = "0.17.0"
directories = "5.0.0"
linkify = "0.9.0"
log = { version = "0.4.17", features = ["std"] }
once_cell = "1.17.1"
open = "4.0.1"
rusqlite = { version = "0.29.0", features = ["bundled", "time"] }
serde_json = "1.0.95"
tokio = { version = "1.27.0", features = ["full"] }
unicode-segmentation = "1.10.1"
unicode-width = "0.1.10"

[dependencies.time]
version = "0.3.20"
features = ["macros", "formatting", "parsing", "serde"]

[dependencies.tokio-tungstenite]
version = "0.18.0"
features = ["rustls-tls-native-roots"]

[dependencies.euphoxide]
git = "https://github.com/Garmelon/euphoxide.git"
rev = "0f217a6279181b0731216760219e8ff0fa01e449"
features = ["bot"]

[dependencies.vault]
git = "https://github.com/Garmelon/vault.git"
rev = "b4cf23b7279770226725c895e482c8eda88c43a7"
features = ["tokio"]
