[package]
name = "cove-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
clap = { version = "3.1.18", features = ["derive"] }
crossterm = { version = "0.23.2", features = ["event-stream"] }
futures = "0.3.21"
thiserror = "1.0.31"
tokio = { version = "1.18.2", features = ["full"] }
toss = { git = "https://github.com/Garmelon/toss.git", rev = "33264b4aec27066e6abb7cc7d15bd680b43fcd5a" }
