[package]
name = "cove-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.56"
chrono = "0.4.19"
clap = { version = "3.1.18", features = ["derive"] }
crossterm = "0.23.2"
futures = "0.3.21"
parking_lot = "0.12.1"
thiserror = "1.0.31"
tokio = { version = "1.19.2", features = ["full"] }
toss = { git = "https://github.com/Garmelon/toss.git", rev = "333cf74fba56080043a13b9f55c0b62695e2fa4a" }
