[package]
name = "cove-macro"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
case = "1.0.0"
proc-macro2 = "1.0.76"
quote = "1.0.35"
syn = "2.0.48"

[lib]
proc-macro = true

[lints]
workspace = true
