[package]
name = "cove-macro"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
case = "1.0.0"
proc-macro2 = "1.0.66"
quote = "1.0.33"
syn = "2.0.29"

[lib]
proc-macro = true
