[package]
name = "cove-macro"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
case = "1.0.0"
proc-macro2 = "1.0.81"
quote = "1.0.36"
syn = "2.0.60"

[lib]
proc-macro = true

[lints]
workspace = true
