[package]
name = "cove-macro"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
case = "1.0.0"
proc-macro2 = "1.0.75"
quote = "1.0.35"
syn = "2.0.47"

[lib]
proc-macro = true
