[package]
name = "cove-macro"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
case = "1.0.0"
proc-macro2 = "1.0.56"
quote = "1.0.27"
syn = "2.0.16"

[lib]
proc-macro = true
