[package]
name = "cove-input"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
crossterm = { workspace = true }
serde = { workspace = true }
serde_either = { workspace = true }
thiserror = { workspace = true }
