[package]
name = "cove-config"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
cove-input = { path = "../cove-input" }
cove-macro = { path = "../cove-macro" }

serde = { workspace = true }
thiserror = { workspace = true }

toml = "0.8.8"

[lints]
workspace = true
